# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Meditation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Meditation
  
  pod 'Masonry'
  pod 'JPSVolumeButtonHandler'
  pod 'MZTimerLabel'
  pod 'Realm'
  pod 'ReactiveObjC'
  pod 'FSCalendar'
  
end
